AddCSLuaFile()

util.AddNetworkString( "ACF_KilledByACF" )
util.AddNetworkString( "ACF_RenderDamage" )
util.AddNetworkString( "ACF_Notify" )
util.AddNetworkString( "ACE_ArmorSummary" )
util.AddNetworkString( "acf_smokewind" )
util.AddNetworkString( "ACE_CamOverride" )
util.AddNetworkString( "ACE_DPStatus" )
util.AddNetworkString( "ACE_Scalable_Network" )
util.AddNetworkString( "ACE_SendMessage" )
util.AddNetworkString( "ACE_Wind" )